controllers/RevisanController.php
<?php

namespace app\controllers;

use app\models\Revisan;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RevisanController implements the CRUD actions for Revisan model.
 */
class RevisanController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Revisan models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Revisan::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Revisan model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Revisan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Revisan();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Revisan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Revisan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Revisan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Revisan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Revisan::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Protectoras;
use yii\data\ActiveDataProvider;
use app\models\Animales;
use app\models\userform;
use kartik\mpdf\Pdf;
use app\models\cartillas;
use app\models\formulario;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'=>  ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionProtectoras(){
        
       $dataProvider = new ActiveDataProvider([
            'query' => Protectoras::find(),
            
        ]);
        
        return $this->render('protectoras',[
        "dataProvider"=>$dataProvider , 
        ]);
    }
    public function actionCruds(){
        
        return $this->render('cruds');
    }
   
    public function actionUser(){
       
        $model = new userform;
                
        if($model->load(Yii::$app->request->post()) && $model->validate()){
            
            Yii::$app->session->setFlash('success','Has introducido los datos correctamente');
            
        }
        return $this->render('userForm',['model'=>$model]);
    }
   
    
      ////////////////////////////////////////////////////////////////////////// FUNCIONES LISTA DE ANIMALES /////////////////////////////////////////////////////////////////////
    
    public function actionListaanimales($codigo){
        
        $dataProvider = new ActiveDataProvider([
            'query' => Animales::find()
            ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes,nombre_mascota,adopcion')
                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
                                       ->andwhere("protectoras.codigo= " . $codigo) 
                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),
                                       
            'pagination' => false,
            ]);
        return $this->render('listaanimales',[
         "dataProvider"=>$dataProvider , 
            
            
        ]);  
    }
//     public function actionListaanimales2(){
//        
//        $dataProvider = new ActiveDataProvider([
//            'query' => Animales::find()
//                 ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes')
//                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
//                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
//                                       ->andwhere("protectoras.codigo=2") 
//                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
//                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),
//            'pagination' => false,
//            ]);
//        return $this->render('listaanimales',[
//         "dataProvider"=>$dataProvider , 
//            
//            
//        ]);  
//    }
//      public function actionListaanimales3(){
//        
//        $dataProvider = new ActiveDataProvider([
//            'query' => Animales::find()
//                 ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes')
//                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
//                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
//                                       ->andwhere("protectoras.codigo=3") 
//                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
//                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),
//            'pagination' => false,
//            ]);
//        return $this->render('listaanimales',[
//         "dataProvider"=>$dataProvider , 
//            
//            
//        ]);  
//    }
//      public function actionListaanimales4(){
//        
//        $dataProvider = new ActiveDataProvider([
//            'query' => Animales::find()
//                 ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes')
//                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
//                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
//                                       ->andwhere("protectoras.codigo=4")
//                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
//                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),
//            'pagination' => false,
//            ]);
//        return $this->render('listaanimales',[
//         "dataProvider"=>$dataProvider , 
//            
//            
//        ]);  
//    }
//      public function actionListaanimales5(){
//        
//        $dataProvider = new ActiveDataProvider([
//            'query' => Animales::find()
//                 ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes')
//                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
//                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
//                                       ->andwhere("protectoras.codigo=5") 
//                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
//                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),
//            'pagination' => false,
//            ]);
//        return $this->render('listaanimales',[
//         "dataProvider"=>$dataProvider , 
//            
//            
//        ]);  
//    }
//      public function actionListaanimales6(){
//        
//        $dataProvider = new ActiveDataProvider([
//            'query' => Animales::find()
//                 ->select('animales.codigo_animal,protectoras.nombre_protectora,tipo_de_animal,edad,raza,cartillas.castrado,cartillas.chip,cartillas.incidentes')
//                                       ->innerjoin('protectoras','protectoras.codigo = animales.codigo')
//                                       ->where('apto_para_adoptar = 1 and formulario.codigo_animal is null') 
//                                       ->andwhere("protectoras.codigo=6")
//                                       ->innerjoin('cartillas','cartillas.codigo_animal = animales.codigo_animal')
//                                       ->leftJoin("formulario", $on="formulario.codigo_animal=animales.codigo_animal"),

controllers/TienenController.php
<?php

namespace app\controllers;

use app\models\Tienen;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TienenController implements the CRUD actions for Tienen model.
 */
class TienenController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Tienen models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Tienen::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tienen model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tienen model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Tienen();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tienen model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tienen model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tienen model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Tienen the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tienen::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/site/_reportView.php
<?php

use yii\helpers\url;
use yii\helpers\Html;



?>

<div class="site-index">
    <div class="body-content solucioncontent ">
        <div class="row  ">
            
          <?= Html::img('imagenes/nuevofavicon2.png',['width' => '8%', 'height' => '8%','style' =>'float:right']);?>
          <h1><p><br><b>Reserva de adopción</b></p></h1> 
             
           
            
            <h3><p><b>Datos de la protectora</b><br></p></h3> 
            <!--     joins del animal-->
            <?= '<b>Protectora: </b>' . $model->codigoAnimal->codigo0->nombre_protectora . "<br>"?>
            <?= '<b>Direccion: </b>' . $model->codigoAnimal->codigo0->direccion . "<br>" ?>
            <?= '<b>Telefono: </b>' . $model->codigoAnimal->codigo0->telefono . "<br>"?>
            <?= '<b>Email: </b>' . $model->codigoAnimal->codigo0->email . "<br>"?>
            
            <h3><p><br><b>Datos de la mascota</b><br></p></h3> 
            
             <?= '<b>Nombre: </b>' .$model->codigoAnimal->nombre_mascota . "<br>" ?> 
            <?= '<b>Edad: </b>' .$model->codigoAnimal->edad . " años " . "<br>" ?> 
            <?= '<b>Raza : </b>' .$model->codigoAnimal->raza . "<br>" ?> 
            <?= '<b>Tipo: </b>' .$model->codigoAnimal->tipo_de_animal . "<br>" ?> 
            
            <h3><p><br><b>Datos del adoptante</b><br></p></h3> 
           
            <!--         datos del formulario-->
            <?='<b>Nombre: </b>' . $model->nombre_usuario . "<br>"?>
            <?='<b>Apellido: </b>' . $model->apellido_usuario . "<br>"?>
            <?='<b>Telefono: </b>' . $model->telefono_usuario . "<br>"?>
            <?='<b>Correo electronico: </b>' . $model->correo . "<br>"?>
            <h3><p><br><b>Firmado:</b><br></p></h3> 
             <?= Html::img('imagenes/logodefinitivo2.png',['width' => '22%', 'height' => '10%']);?>
           
        </div> 
        
    </div>
</div>

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/cruds.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;



$this->title = 'Información';

?>
<div class="container">
    
    <div class="body-content">
        <div class="jumbotron text-center bg-transparent">
            <h1 class="display-4" style="padding-top: 15px">Datos generales</h1>
        </div>
        <div class="row">
            
            <div class="col-sm-6 col-md-4 "> 
                <div class="card alturacruds polaroid ">
                    
                    <div class="card-body tarjeta">
                        
                        <h3>Animales</h3>
                        <p></p>
                           
                            <?= Html::a(Html::img('@web/imagenes/animalesCRUDS.png',['width'=>'100%','height'=>'100%']),['/animales/index'],['class'=> 'imageneshome'])?>

                    </div>
                </div>
             </div>  
           
             <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Animales apadrinados</h3>    
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/animalesAP.png',['width'=>'100%','height'=>'100%']),['/apadrinan/index'],['class'=> 'imageneshome'])?>
                          
                    </div>
                </div>
             </div>  
            
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Cartillas de los animales</h3>
                        <p></p>                        
                        <?= Html::a(Html::img('@web/imagenes/cartillaP.png',['width'=>'100%','height'=>'100%']),['/cartillas/index'],['class'=> 'imageneshome']) ?>
                        
                    </div>
                </div>
             </div>    
         
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    
                    <div class="card-body tarjeta">
                        
                        <h3>Clientes</h3>
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/clientes.png',['width'=>'100%','height'=>'100%']),['/clientes/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
             <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Protectoras</h3>    
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/iconoProtectora.png',['width'=>'100%','height'=>'100%']),['/protectoras/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Animales revisados por los veterinarios</h3>
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/animalesRevisados.png',['width'=>'100%','height'=>'100%']),['/revisan/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
            </div> 
            
                 <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    
                    <div class="card-body tarjeta">
                        
                        <h3>Veterinario que trabaja en cada protectora</h3>
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/animalesdeP.png',['width'=>'100%','height'=>'100%']),['/tienen/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
             <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Vacunas</h3>    
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/vacunasP.png',['width'=>'100%','height'=>'100%']),['/vacunas/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturacruds polaroid">
                    <div class="card-body tarjeta">
                        <h3>Veterinarios</h3>
                        <p></p>
                        
                         <?= Html::a(Html::img('@web/imagenes/veterinarios.png',['width'=>'100%','height'=>'100%']),['/veterinarios/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
            </div> 
            
    </div>
    </div> 
</div> 

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/formulario.php
<?php

use yii\helpers\url;
use yii\helpers\Html;

?>

<h1>Formulario</h1>
<h3><?= $mensaje ?></h3>

<?= Htmll::beginform(
        url::toRoute("site/request"), //action
        "get", //method
        ['class'=> 'form-inline'] //options
        
        );

?>
<div class ="form-group">

<?= Html::endForm("Introduce tu nombre", "nombre") ?>
<?= Html::textInput("nombre",null,["class"=> "form-control"])?>
    
    
</div>

<?= Html::submitInput("enviar nombre",["class" => "btn btn-primary"])?>

<?= Html::endForm() ?>

views/site/index.php
<?php

//use yii\widgets\ListView;

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Home';
?>





<div class="pt-5"> </div>

<h1 class ="titulo">¿Quiénes somos?</h1>

<div class="pt-4"> </div>

<p class="texto">Adopta & rescata somos una empresa sin ánimo de lucro, nuestro único objetivo es ayudar al máximo de protectoras posibles a que adopten a sus animalitos y también de alguna manera a las personas que estén interesados en adoptar o apadrinar a un animal.</p>
<p class="texto">En nuestra página podrás encontrar una variedad de protectoras con las que estamos trabajando.</p>

<h2 class ="titulo">¿Cuál es nuestro objetivo?</h2>
<div class="pt-4"> </div>

<p class="texto">Nuestro objetivo es trabajar con todas las protectoras posibles de diferentes regiones, facilitando de esa manera que cualquier persona de un vistazo encuentre todas las protectoras y de esa manera encontrar al acompañante perfecto en su vida. </p>

<div class="pt-5"> </div>


<div class="container-fluid">
    <div class="row stilobody">
        <div class=" col-sm-13 col-md-13 col-lg-13 ">

            <div class="size-carousel-flex polaroid " style="background-color: #d27979">

                <!--Carousel Wrapper-->
                <div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active "></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    

                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active" >
                            <div class="d-flex align-content-around" >
                                <div class="p-0">  <?= Html::a(Html::img('@web/imagenes/aspacancarrusel.png'), ['site/listaanimales', 'codigo' => '2'], ['class' => 'imageneshome']) ?></div>
    <!--                           <div class="align-self-center"> <p class="text-center centrarp">En Aspacan hay una agran variedad de perritos que les han abandonado esperando un hogar, Adopta un perrito. </p>  </div>-->
                                <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2898.5846266600142!2d-3.4160235842282307!3d43.40661057635836!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd4eea9b8c61014d%3A0xc5f55cd8ac18b3dc!2sAspacan%20protectora%20y%20adopci%C3%B3n%20canina!5e0!3m2!1ses!2ses!4v1655135434633!5m2!1ses!2ses" width="500" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
                            </div>                      
                        </div>
                        <div class="carousel-item">
                             <div class="d-flex align-content-around" >
                                <div class="p-0"> <?= Html::a(Html::img('@web/imagenes/carruselT.png'), ['site/listaanimales', 'codigo' => '5'], ['class' => 'imageneshome']) ?></div>
                                <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d371337.38377261936!2d-4.604292050000042!3d43.35457710000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd49158cdfc9535b%3A0xf590322aa8dec7!2sRefugio%20Canino%20Torres%20Torrelavega!5e0!3m2!1ses!2ses!4v1655134647451!5m2!1ses!2ses" width="500" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
                            </div> 
                        </div>
                        <div class="carousel-item">
                           <div class="d-flex align-content-around" >
                                <div class="p-0"> <?= Html::a(Html::img('@web/imagenes/carruselAS.png'), ['site/listaanimales', 'codigo' => '6'], ['class' => 'imageneshome']) ?></div>
                                <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2895.326355979762!2d-3.852917784226719!3d43.4746591719749!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd49493335de3627%3A0x6e6c5b02b2d0684f!2sASPROAN%20Santander%20-%20Refugio%20Canino!5e0!3m2!1ses!2ses!4v1655135194633!5m2!1ses!2ses" width="500" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
     <!--                           <div class="align-self-center"> <p class="text-center centrarp">La asociación Perrucos Cantabria es una protectora que recoge todos los perros abandonados y busca a familias para que los perros puedan tener una mejor vida. </p>  </div>-->
                            </div>  
                        </div>
                       



                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon " aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon " aria-hidden="true"></span>
                        <span class="sr-only ">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

  